### ISSUE TITLE
数据库有吗? 

### ISSUE THREAD

**Issue by Caladog** [jackchen0120/ip-nodejs-api#1]
登录的帐号密码是什么？怎么可以登录看看？

**Comment by jackchen0120** [comment]
> 登录的帐号密码是什么？怎么可以登录看看？

可以免密登录，或第三方登录比如github

**Comment by Caladog** [comment]
收到，谢谢



王超
13964868911
无争，也有属于我的世界 @ 2017


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jackchen0120/ip-nodejs-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月20日(星期二) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jackchen0120/ip-nodejs-api] 数据库有吗?  (#1)





  
登录的帐号密码是什么？怎么可以登录看看？
  
可以免密登录，或第三方登录比如github
